hparams = {
    'batch_size': 8,
    'lr': 0.0001,  # 0.0001,  # 5e-4,
    'weight_decay': 0.00001,
    'dropout': 0.0,
    'description': 'NRMS lr=1e-4, with weight_decay',
    'saved_model_path': '',
    # 'pretrained_model': '/Users/shhirsch/git/Generate-Tips/data/glove.6B/glove.6B.300d.txt',
    # 'pretrained_model': '/mnt/nas/shhirsch/glove.6B/glove.6B.300d.txt',
    # 'pretrained_model': '/data/ebay/data/shhirsch/personalization/glove.6B/glove.6B.300d.txt',
    'embedding_type': 'w2v',
    # 'embedding_type': 'llm',
    'pretrained_model': {
        'glove': '/data/ebay/data/shhirsch/personalization/glove.6B/glove.6B.300d.txt',
        'w2v': '/sise/home/lilachzi/PersonzalizedReviews/w2v_ciao_amazon/w2v_ciao_amazon.kv'
    },
    'task': 'classification',
    'dct_size': 'auto',
    'nhead': 20,
    'llm_nhead': 16,
    'embed_size': 300,
    # 'attn_hidden_dim': 200,
    'encoder_size': 300,
    'v_size': 200,
    'npratio': 3,
    'his_type': 'write',
    # 'his_type': 'like',
    # 'his_type': 'write-like',
    # 'his_type': 'combined',
    # 'his_size': 15,
    # 'llm_his_size': 15,
    'his_size': 15,
    # 'llm_his_size': 30,
    'write_his_size': 10,
    'like_his_size': 35,
    # 'his_size': 10,
    # 'llm_his_size': 10,
    # 'review_size': 350,
    'review_size': 350,
    'llm_review_size': 768,
    'train_method': '1',
    # 'llm_summary': 'llama',
    # 'llm_summary': 'gpt_aspects'
    'llm_summary': None,
    # 'use_candidates': False,
    'use_candidates': True,
    'candidates_category': 'Internet',
    'num_candidates': 20
}
